E0127 11:38:26.798000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [571/0] failed while attempting to run meta for aten.pixel_shuffle.default
E0127 11:38:26.798000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [571/0] Traceback (most recent call last):
E0127 11:38:26.798000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [571/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0127 11:38:26.798000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [571/0]     r = func(*args, **kwargs)
E0127 11:38:26.798000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [571/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0127 11:38:26.798000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [571/0]     return self._op(*args, **kwargs)
E0127 11:38:26.798000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [571/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0127 11:38:26.798000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [571/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 6488, in meta_pixel_shuffle
E0127 11:38:26.798000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [571/0]     len(self.shape) > 2 and self.shape[-3] % (upscale_factor * upscale_factor) == 0
E0127 11:38:26.798000 703210 site-packages/torch/_subclasses/fake_tensor.py:2380] [571/0] AssertionError: Invalid input shape for pixel_shuffle: torch.Size([1, 32, 2*((s1//4)) + 5, 2*(((s2//4)) + 2)*(((s3//4)) + 2) + 1, 1]) with upscale_factor = 2
