E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0] failed while attempting to run meta for aten.mul.Tensor
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0] Traceback (most recent call last):
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     r = func(*args, **kwargs)
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     return self._op(*args, **kwargs)
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/wrappers.py", line 305, in _fn
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     result = fn(*args, **kwargs)
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/wrappers.py", line 146, in _fn
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     result = fn(**bound.arguments)
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/__init__.py", line 1085, in _ref
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     a, b = _maybe_broadcast(a, b)
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]            ~~~~~~~~~~~~~~~~^^^^^^
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/__init__.py", line 427, in _maybe_broadcast
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     common_shape = _broadcast_shapes(
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]         *(t.shape if isinstance(t, TensorLike) else None for t in args)
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     )
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/__init__.py", line 415, in _broadcast_shapes
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     torch._check(
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     ~~~~~~~~~~~~^
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]         common_shape[idx] == shape[idx],
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     ...<2 lines>...
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]         f"should be broadcastable to {common_shape}",
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     )
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     ^
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     _check_with(RuntimeError, cond, message)
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0]     raise error_type(message_evaluated)
E0205 10:41:11.754000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [67/0] RuntimeError: Attempting to broadcast a dimension of length 10 at -4! Mismatching argument at index 1 had torch.Size([1, 10, 1, 1, 1]); but expected shape should be broadcastable to [1, 3, 14, 14, 1]
