E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0] failed while attempting to run meta for aten.mul.Tensor
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0] Traceback (most recent call last):
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     r = func(*args, **kwargs)
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     return self._op(*args, **kwargs)
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/wrappers.py", line 305, in _fn
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     result = fn(*args, **kwargs)
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_prims_common/wrappers.py", line 146, in _fn
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     result = fn(**bound.arguments)
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/__init__.py", line 1085, in _ref
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     a, b = _maybe_broadcast(a, b)
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]            ~~~~~~~~~~~~~~~~^^^^^^
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/__init__.py", line 427, in _maybe_broadcast
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     common_shape = _broadcast_shapes(
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]         *(t.shape if isinstance(t, TensorLike) else None for t in args)
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     )
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_refs/__init__.py", line 415, in _broadcast_shapes
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     torch._check(
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     ~~~~~~~~~~~~^
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]         common_shape[idx] == shape[idx],
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     ...<2 lines>...
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]         f"should be broadcastable to {common_shape}",
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     )
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     ^
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     _check_with(RuntimeError, cond, message)
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0]     raise error_type(message_evaluated)
E0204 16:25:32.758000 2827036 site-packages/torch/_subclasses/fake_tensor.py:2380] [468/0] RuntimeError: Attempting to broadcast a dimension of length 64 at -1! Mismatching argument at index 1 had torch.Size([64]); but expected shape should be broadcastable to [1, 108, 36]
