E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0] failed while attempting to run meta for aten.avg_pool2d.default
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0] Traceback (most recent call last):
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_subclasses/fake_tensor.py", line 2376, in _dispatch_impl
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     r = func(*args, **kwargs)
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_ops.py", line 749, in __call__
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     return self._op(*args, **kwargs)
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]            ~~~~~~~~^^^^^^^^^^^^^^^^^
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 2628, in meta_avg_pool2d
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     pool2d_shape_check(
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     ~~~~~~~~~~~~~~~~~~^
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]         input,
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]         ^^^^^^
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     ...<13 lines>...
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]         memory_format,
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]         ^^^^^^^^^^^^^^
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     )
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     ^
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/_meta_registrations.py", line 4288, in pool2d_shape_check
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     torch._check(
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     ~~~~~~~~~~~~^
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]         outputWidth >= 1 and outputHeight >= 1,
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     ...<2 lines>...
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]         "Output size is too small",
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     )
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     ^
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1651, in _check
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     _check_with(RuntimeError, cond, message)
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]   File "/home/sahanp/.conda/envs/popcorn/lib/python3.13/site-packages/torch/__init__.py", line 1633, in _check_with
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0]     raise error_type(message_evaluated)
E0205 10:40:59.601000 2062045 site-packages/torch/_subclasses/fake_tensor.py:2380] [53/0] RuntimeError: Given input size: (s0x(((((s1//2)) + 1)*(((s2//2)) + 1)*(((s3//2)) + 1))//2)x1). Calculated output size: (s0x(((((s1//2)) + 1)*(((s2//2)) + 1)*(((s3//2)) + 1))//4)x0). Output size is too small
